name: Build Go App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'

    - name: Build Windows EXE
      run: GOOS=windows GOARCH=amd64 go build -v -o calculadora.exe main.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculadora-windows
        path: calculadora.exe
